### ISSUE TITLE
Improve readability of widget parameters

### ISSUE THREAD

**Issue by KenT2** [dddomodossola/gui#10]
One of the Widget parameters is horizontal/vertical which is True or False. It would be much more readable to define constants HORIZONTAL and VERTICAL

**Comment by dddomodossola** [comment]
Done. The constants are named LAYOUT_VERTICAL and LAYOUT_HORIZONTAL. Defined in Widget class. Please feedback in order to close issue.

**Comment by KenT2** [comment]
Much better, thanks
