### ISSUE TITLE
Icons and filenames in FileSelectionDialog

### ISSUE THREAD

**Issue by KenT2** [dddomodossola/gui#19]
In the file selection dialog I think it would be more intuitive if clicking on the directory icon opened that directory and clicking on the filename does the selection of files and directories, rather than the other way round.

Clicking on a file icon would probably do nothing.

**Comment by dddomodossola** [comment]
Done. Please feedback in order to close issue.

**Comment by KenT2** [comment]
Works and much more intuitive, thanks.

**Comment by dddomodossola** [comment]
;-) Thank you for the suggestions

**Comment by nzjrs** [comment]
I think something broke. If you select a file and click OK, when you come back to the main window the logo.png is broken / missing
