### ISSUE TITLE
Setting the initial value of the DropDown

### ISSUE THREAD

**Issue by KenT2** [dddomodossola/gui#23]
I cannot work out how to reliably set the initial value of a DropDown. A set_value method would be useful as it would allow the displayed value to be changed by the App. Same will probably apply to the SpinBox, Slider and Colour Picker etc.

**Comment by dddomodossola** [comment]
Hi Ken,
At this commit df39e1472dfee62b03d7b42e032487231cf244a1 you can find these functions. Please feedback and eventually close this issue if solved.

**Comment by dddomodossola** [comment]
Hi can, have you tested these changes?

**Comment by KenT2** [comment]
All OK, thanks
