### ISSUE TITLE
ability to update widgets from code

### ISSUE THREAD

**Issue by nzjrs** [dddomodossola/gui#24]
Label has set_text that can be called from within the gui. I would like

Slider.set_value()
SpinBox.set_value()

so that I can update the GUI to reflect the state of my program

**Comment by dddomodossola** [comment]
Good suggestion. Done in this commit 3772e80bbec38cec25a5b9e69089c4c892e4109c.
Please give a feedback for this.

**Comment by nzjrs** [comment]
seems to work, thanks.
